name: Auto Video Generator

on:
  push:
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ffmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Debug (see files)
        run: |
          echo "Images folder:"
          ls -la images

      - name: Create Video
        run: |
          mkdir -p videos
          IMAGE=$(find images -type f | head -n 1)
          echo "Using image: $IMAGE"
          ffmpeg -loop 1 -i "$IMAGE" -c:v libx264 -t 5 -pix_fmt yuv420p videos/output.mp4

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: output-video
          path: videos/output.mp4
