name: Auto Video Generator

on:
  push:
    paths:
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ffmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Debug files
        run: ls images

      - name: Create Video
        run: |
          mkdir -p videos
          FILE=$(ls images | head -n 1)
          ffmpeg -loop 1 -i images/$FILE -c:v libx264 -t 5 -pix_fmt yuv420p videos/output.mp4

      - name: Upload Video
        uses: actions/upload-artifact@v3
        with:
          name: output-video
          path: videos/output.mp4
