name: Video Creator Action
on:
  repository_dispatch:
    types: [create_video_signal]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Create Video
        env:
          IMAGE_URL: ${{ github.event.client_payload.image_url }}
          VOICE_TEXT: ${{ github.event.client_payload.voice_text }}
          VIDEO_NAME: ${{ github.event.client_payload.video_name }}
        run: python main.py
      - name: Push to Repo
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add videos/*.mp4
          git commit -m "New video"
          git push
